# Generated by Django 5.2 on 2025-08-17 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0002_announcement_announcementreaction_roommembership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Room Name'),
        ),
    ]
